
int128 : int128.cpp
	g++ -std=gnu++14  -O2 -o $@ $^ -I ..

t10 : t10.cpp
	g++ -std=gnu++14  -O2 -o $@ $^ -I ..

t11 : t11.cpp
	g++ -std=gnu++14 -g -O3 -o $@ $^ -I ..

t12 : t12.cpp
	g++ -std=gnu++14 -g -O3 -o $@ $^ -I .. -I ../../mina -I ../../yesod
