CC=g++
CXXFLAGS=-std=c++1y  -I.. -I../../yesod -lgmp

t4 : t4.cpp
	$(CC) $(CXXFLAGS) -o $@ $^

t3 : t3.cpp
	$(CC) $(CXXFLAGS) -o $@ $^

t1 : t1.cpp
	$(CC) $(CXXFLAGS) -o $@ $^

magic_div : magic_div.cpp
	$(CC) $(CXXFLAGS) -o $@ $^
