CC=g++
CXXFLAGS+=-std=gnu++1y -I.. -I../yesod

p_array_test: p_array_test.cpp
	$(CC) $(CXXFLAGS) -g -o $@ $^

sparse_vector_test: sparse_vector_test.cpp
	$(CC) $(CXXFLAGS) -g -o $@ $^

string_map_test: string_map_test.cpp
	$(CC) $(CXXFLAGS) -g -o $@ $^
