		{nullptr, 0, nullptr},
		{"broadcast", 9, &option<int, level, SO_BROADCAST>::set},
		{"passcred", 8, &option<int, level, SO_PASSCRED>::set},
		{"reuseport", 9, &option<int, level, SO_REUSEPORT>::set},
		{"sndtimeo", 8, &option<::timeval, level, SO_SNDTIMEO>::set},
		{nullptr, 0, nullptr},
		{"sndbuf", 6, &option<int, level, SO_SNDBUF>::set},
		{"keepalive", 9, &option<int, level, SO_KEEPALIVE>::set},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"priority", 8, &option<int, level, SO_PRIORITY>::set},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"linger", 6, &option<::linger, level, SO_LINGER>::set},
		{"reuseaddr", 9, &option<int, level, SO_REUSEADDR>::set},
		{"type", 4, &option<void, level, SO_TYPE>::set},
		{"error", 5, &option<void, level, SO_ERROR>::set},
		{"debug", 5, &option<int, level, SO_DEBUG>::set},
		{nullptr, 0, nullptr},
		{"sndbufforce", 11, &option<int, level, SO_SNDBUFFORCE>::set},
		{"rcvbuf", 6, &option<int, level, SO_RCVBUF>::set},
		{nullptr, 0, nullptr},
		{"rcvtimeo", 8, &option<::timeval, level, SO_RCVTIMEO>::set},
		{"no_check", 8, &option<int, level, SO_NO_CHECK>::set},
		{"bsdcompat", 9, &option<int, level, SO_BSDCOMPAT>::set},
		{nullptr, 0, nullptr},
		{"oobinline", 9, &option<int, level, SO_OOBINLINE>::set},
		{"rcvlowat", 8, &option<int, level, SO_RCVLOWAT>::set},
		{"rcvbufforce", 11, &option<int, level, SO_RCVBUFFORCE>::set},
		{"peercred", 8, &option<int, level, SO_PEERCRED>::set},
		{"dontroute", 9, &option<int, level, SO_DONTROUTE>::set},
		{"sndlowat", 8, &option<int, level, SO_SNDLOWAT>::set}
