		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"timestampns", 11, option_entry<bool, level, SO_TIMESTAMPNS>::impl},
		{"rcvtimeo", 8, option_entry<::timeval, level, SO_RCVTIMEO>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"dontroute", 9, option_entry<bool, level, SO_DONTROUTE>::impl},
		{"security_authentication", 23, option_entry<void, level, SO_SECURITY_AUTHENTICATION>::impl},
		{"broadcast", 9, option_entry<bool, level, SO_BROADCAST>::impl},
		{nullptr, 0, nullptr},
		{"no_check", 8, option_entry<bool, level, SO_NO_CHECK>::impl},
		{nullptr, 0, nullptr},
		{"bindtodevice", 12, option_entry<string_tag, level, SO_BINDTODEVICE>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"domain", 6, option_entry<ro_tag<int>, level, SO_DOMAIN>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"peek_off", 8, option_entry<int, level, SO_PEEK_OFF>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"mark", 4, option_entry<int, level, SO_MARK>::impl},
		{"rxq_ovfl", 8, option_entry<bool, level, SO_RXQ_OVFL>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"reuseport", 9, option_entry<bool, level, SO_REUSEPORT>::impl},
		{nullptr, 0, nullptr},
		{"reuseaddr", 9, option_entry<bool, level, SO_REUSEADDR>::impl},
		{nullptr, 0, nullptr},
		{"type", 4, option_entry<ro_tag<int>, level, SO_TYPE>::impl},
		{"wifi_status", 11, option_entry<bool, level, SO_WIFI_STATUS>::impl},
		{nullptr, 0, nullptr},
		{"detach_filter", 13, option_entry<bool, level, SO_DETACH_FILTER>::impl},
		{"nofcs", 5, option_entry<bool, level, SO_NOFCS>::impl},
		{"sndlowat", 8, option_entry<ro_tag<int>, level, SO_SNDLOWAT>::impl},
		{"attach_filter", 13, option_entry<::sock_fprog, level, SO_ATTACH_FILTER>::impl},
		{nullptr, 0, nullptr},
		{"lock_filter", 11, option_entry<bool, level, SO_LOCK_FILTER>::impl},
		{nullptr, 0, nullptr},
		{"security_encryption_network", 27, option_entry<void, level, SO_SECURITY_ENCRYPTION_NETWORK>::impl},
		{"sndbufforce", 11, option_entry<int, level, SO_SNDBUFFORCE>::impl},
		{"select_err_queue", 16, option_entry<bool, level, SO_SELECT_ERR_QUEUE>::impl},
		{nullptr, 0, nullptr},
		{"priority", 8, option_entry<int, level, SO_PRIORITY>::impl},
		{"rcvbuf", 6, option_entry<int, level, SO_RCVBUF>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"error", 5, option_entry<ro_tag<int>, level, SO_ERROR>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"rcvbufforce", 11, option_entry<int, level, SO_RCVBUFFORCE>::impl},
		{nullptr, 0, nullptr},
		{"keepalive", 9, option_entry<bool, level, SO_KEEPALIVE>::impl},
		{nullptr, 0, nullptr},
		{"security_encryption_transport", 29, option_entry<void, level, SO_SECURITY_ENCRYPTION_TRANSPORT>::impl},
		{nullptr, 0, nullptr},
		{"acceptconn", 10, option_entry<ro_tag<int>, level, SO_ACCEPTCONN>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"oobinline", 9, option_entry<bool, level, SO_OOBINLINE>::impl},
		{"passcred", 8, option_entry<bool, level, SO_PASSCRED>::impl},
		{"peersec", 7, option_entry<ro_tag<string_tag>, level, SO_PEERSEC>::impl},
		{nullptr, 0, nullptr},
		{"sndtimeo", 8, option_entry<::timeval, level, SO_SNDTIMEO>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"busy_poll", 9, option_entry<int, level, SO_BUSY_POLL>::impl},
		{nullptr, 0, nullptr},
		{"timestamp", 9, option_entry<bool, level, SO_TIMESTAMP>::impl},
		{"timestamping", 12, option_entry<int, level, SO_TIMESTAMPING>::impl},
		{"passsec", 7, option_entry<bool, level, SO_PASSSEC>::impl},
		{nullptr, 0, nullptr},
		{"bsdcompat", 9, option_entry<void, level, SO_BSDCOMPAT>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"bpf_extensions", 14, option_entry<ro_tag<int>, level, SO_BPF_EXTENSIONS>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"max_pacing_rate", 15, option_entry<int, level, SO_MAX_PACING_RATE>::impl},
		{nullptr, 0, nullptr},
		{"rcvlowat", 8, option_entry<int, level, SO_RCVLOWAT>::impl},
		{nullptr, 0, nullptr},
		{"peercred", 8, option_entry<::ucred, level, SO_PEERCRED>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"linger", 6, option_entry<::linger, level, SO_LINGER>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"peername", 8, option_entry<ro_tag<string_tag>, level, SO_PEERNAME>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"debug", 5, option_entry<bool, level, SO_DEBUG>::impl},
		{nullptr, 0, nullptr},
		{nullptr, 0, nullptr},
		{"sndbuf", 6, option_entry<int, level, SO_SNDBUF>::impl},
		{"protocol", 8, option_entry<ro_tag<int>, level, SO_PROTOCOL>::impl},
